server:
  url: http://server:9898
  api_key: opl_445230515cedb751d410dce137df59865bf567309fcc4c028381c0f1cd719af8
agent:
  interval_seconds: 5
  self_upgrade: false
  
tags:
  env: prod
  region: us-west-1
  role: go-agent
  name: agent-config2
  owner: team-a