server:
  url: http://server:9898
  api_key: opl_a4e85dd5b6d16a283881e8f78c14bda4f21d7734d48311fcb8697b7e1139ef8f
agent:
  interval_seconds: 5
  self_upgrade: false
  log_file_path: /logs/random.log
  log_collection_interval_seconds: 5
  
tags:
  env: preprod
  region: us-west-1
  role: go-agent
  name: agent-config1
  owner: team-a