server:
  url: http://server:9898
  api_key: opl_5a65ac5c00f9420c281fb5d945ab22c8bdf76f9b7a6a6056adb414058e8a1385

account_id: default

agent:
  interval_seconds: 5
  self_upgrade: false
  log_file_path: /logs/random.log
  log_collection_interval_seconds: 5
  logs:
    - name: random_app_log
      type: file
      path: /logs/random.log
    - name: system_logs
      type: directory
      path: /var/log
      include:
        - syslog
        - auth.log
      exclude:
        - "*.gz"
    - name: kernel_logs
      type: command
      command: dmesg --ctime
  
tags:
  env: preprod
  region: us-west-1
  role: go-agent
  name: agent-config1
  owner: team-a