server:
  url: http://server:9898
  api_key: opl_ecdd8b56f395948b4682be3be39a59d817207bd93ccd67b434cef38793731ed9

agent:
  interval_seconds: 5
  self_upgrade: false
  log_collection_interval_seconds: 5
  logs:
    - name: random_app_log
      type: file
      path: /logs/random.log
    - name: system_logs
      type: directory
      path: /var/log
      include:
        - syslog
        - auth.log
      exclude:
        - "*.gz"
    - name: kernel_logs
      type: command
      command: dmesg --ctime
  
tags:
  env: test
  region: us-west-2
  role: go-agent
  name: agent-config2
  owner: team-c