server:
  url: http://server:9898
  api_key: opl_c0a10bc7604c8ec89c671dad3db081e67b17a16f6e5b4bc2e8ced81f12d31a11
agent:
  interval_seconds: 5
  self_upgrade: false
  log_file_path: /var/log/opslens-pulse/agent.log
  log_collection_interval_seconds: 10
  
tags:
  env: prod
  region: us-west-1
  role: go-agent
  name: agent-config2
  owner: team-a