services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: opslens-clickhouse
    networks:
      - opslens-net
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=ch_password
      - CLICKHOUSE_DB=opslens
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse-db/init:/docker-entrypoint-initdb.d
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  postgres:
    image: postgres:16
    container_name: opslens-postgres
    networks:
      - opslens-net
    environment:
      POSTGRES_USER: opslens
      POSTGRES_PASSWORD: opslens_password
      POSTGRES_DB: opslens
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U opslens"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: golang:1.25.6-alpine
    container_name: opslens-server
    working_dir: /app
    volumes:
      - .:/app
      - ./server-config.yaml:/etc/opslens-pulse/server-config.yaml
    command: sh -c "go run ./server"
    ports:
      - "9898:9898"
    networks:
      - opslens-net
    environment:
      - JWT_SECRET=supersecret
      - POSTGRES_PASSWORD=opslens_password
      - CLICKHOUSE_PASSWORD=ch_password
    depends_on:
      clickhouse:
        condition: service_healthy
      postgres:
        condition: service_healthy

networks:
  opslens-net:
    driver: bridge

volumes:
  clickhouse-data:
  postgres_data: