services:
  server:
    image: golang:1.22
    container_name: opslens-server
    working_dir: /app
    volumes:
      - ./:/app      # Mount the whole repo
      - ./server-config.yaml:/etc/opslens-pulse/server-config.yaml
    command: go run server/main.go
    ports:
      - "9898:9898"

  agent1:
    image: golang:1.22
    working_dir: /app
    hostname: opslens-agent1
    container_name: opslens-agent1
    volumes:
      - ./:/app      # Mount the whole repo
      - ./agent-config1.yaml:/etc/opslens-pulse/agent-config.yaml
    command: go run agent/main.go
    depends_on:
      - server
  
  agent2:
    image: golang:1.22
    working_dir: /app
    hostname: opslens-agent2
    container_name: opslens-agent2
    volumes:
      - ./:/app      # Mount the whole repo
      - ./agent-config2.yaml:/etc/opslens-pulse/agent-config.yaml
    command: go run agent/main.go
    depends_on:
      - server

  agent3:
    image: golang:1.22
    working_dir: /app
    hostname: opslens-agent3
    container_name: opslens-agent3
    volumes:
      - ./:/app      # Mount the whole repo
      - ./agent-config3.yaml:/etc/opslens-pulse/agent-config.yaml
    command: go run agent/main.go
    depends_on:
      - server

  agent4:
    image: golang:1.22
    working_dir: /app
    hostname: opslens-agent4
    container_name: opslens-agent4
    volumes:
      - ./:/app      # Mount the whole repo
      - ./agent-config4.yaml:/etc/opslens-pulse/agent-config.yaml
    command: go run agent/main.go
    depends_on:
      - server