FROM golang:1.25.6-alpine

WORKDIR /app

RUN apk add --no-cache git

# Copy go mod first (cache)
COPY go.mod go.sum ./
RUN go mod download

# Copy everything (server + ui)
COPY . .

# Expose port
EXPOSE 9898

# Run directly
CMD ["go", "run", "./server"]